site_name: TraditionalSave2
theme:
  name: material
  logo: docsAssets/Icon.png
  favicon: docsAssets/Icon.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    search: fontawesome/solid/search
  palette:
    scheme: slate
    primary: custom
    accent: custom

  features:
      - navigation.instant
      - navigation.instant.prefetch
      - navigation.instant.progress
      - navigation.tabs 
      - navigation.sections
      - navigation.path
      - navigation.indexes
      - navigation.top
      - navigation.footer
      - header.autohide
      - search.suggest
      - search.highlight
  font:
    text: Roboto
    code: Roboto Mono


markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_css:
  - docsAssets/style.css
  - docsAssets/colors.css
  - docsAssets/smooth-scroll.css

extra:
  version:
    provider: mike
    default: stable
    alias: true
    
plugins:
  - mike:


nav:
  - Home: index.md
  - The Basics:
    - Quick Start:
      - Why This?: the-basics/Quick-Start/why-this.md
      - Download: the-basics/Quick-Start/download.md
      - Getting Started: the-basics/Quick-Start/getting-started.md
    - Fundamentals:
      - Stores: the-basics/Fundamentals/Stores.md
      - Profiles: the-basics/Fundamentals/Profiles.md
      - Loaders: the-basics/Fundamentals/Loaders.md
      - PlayerProfiles: the-basics/Fundamentals/PlayerProfiles.md
    - Specifics:
      - Binding To Loaders: the-basics/Specifics/Binding-To-Loaders.md
      - Locked Loaders: the-basics/Specifics/Locked-Loaders.md
      - Profile Methods: the-basics/Specifics/Profile-Methods.md
      - Updating Loaders: the-basics/Specifics/Updating-Loaders.md
    - Best Practices:
      - Global Files: the-basics/Best-Practices/Global-Files.md
  - API Reference:
    - API-Reference/index.md
    - Types:
      - Error: API-Reference/Types/Error.md
      - Key: API-Reference/Types/Key.md
      - FileKey: API-Reference/Types/FileKey.md
      - StoreConfig: API-Reference/Types/StoreConfig.md
    - Objects:
      - Store: API-Reference/Objects/Store.md
      - Profile: API-Reference/Objects/Profile.md
      - Loader: API-Reference/Objects/Loader.md
      - PlayerProfiles: API-Reference/Objects/PlayerProfiles.md